
- name: check if openHAB component is installed - {{component}}
  stat: path={{ openhab_install_dir }}/{{component}}/{{ openhab_version }}
  #ignore_errors: yes
  register: openhab_ls

- name: download openHAB {{component}}
  get_url: >
    url=https://bintray.com/artifact/download/openhab/bin/distribution-{{openhab_version}}-{{component}}.zip
    dest={{ ansible_env.HOME }}/downloads/openhab-{{component}}-v{{openhab_version}}.zip
    validate_certs=no
  when: openhab_ls.stat.exists == false

- name: create openHAB {{component}} directory
  file: >
    state=directory
    path={{ openhab_install_dir }}/{{component}}/{{openhab_version}}
  when: openhab_ls.stat.exists == false

- name: unzip openHAB {{component}} download
  unarchive: >
    src={{ ansible_env.HOME }}/downloads/openhab-{{component}}-v{{openhab_version}}.zip
    dest={{ openhab_install_dir }}/{{component}}/{{openhab_version}}/
    copy=no
  when: openhab_ls.stat.exists == false
