- name: Check if my_package is installed
  command: dpkg-query -W node
  register: node_check_deb
  failed_when: node_check_deb.rc > 1
  changed_when: node_check_deb.rc == 1

- name: download node
  get_url: 
          url=http://node-arm.herokuapp.com/node_latest_armhf.deb 
          dest=~/downloads/node_latest_armhf.deb
  when: node_check_deb.rc == 1

- name: Install node
  apt: deb="~/downloads/node_latest_armhf.deb"
  become: yes
  when: node_check_deb.rc == 1

- name: Install "request" node.js package.
  become: yes
  become_user: openhab
  npm: name=request path={{openhab_configuration_dir}}/scripts

- name: Install "object-assign" node.js package.
  become: yes
  become_user: openhab
  npm: name=object-assign path={{openhab_configuration_dir}}/scripts

- name: Install "es6-promise" node.js package.
  become: yes
  become_user: openhab
  npm: name=es6-promise path={{openhab_configuration_dir}}/scripts
