- name: Install required mosquitto packages
  apt: name={{item}} state=installed
  become: yes
  with_items:
      - mosquitto
  become: yes

- name: mosquitto config file
  template: dest=/etc/mosquitto/mosquitto.conf src=../templates/mosquitto.conf

  # Password set manually like this:
  # sudo mosquitto_passwd -c /etc/mosquitto/passwd mosquitto

- name: Install required PIP-packages
  become: yes
  pip: name={{item}}
  with_items:
    - schedule
    - datetime
    - paho-mqtt
    - time
    - git+https://github.com/jdhorne/pycarwings2.git

- name: Clone github repo
  repo: git://github.com/glynhudson/leaf-python-mqtt.git
  become: yes
  clone: yes
  dest: /etc/leaf-python-mqtt

- name: leaf-python config file
  template: dest=/etc/leaf-python-mqtt/config.ini src=../templates/config.ini
  become: yes
